### PR TITLE
Stop user HerokuController from clobbering config

### LINKED ISSUE #5: Unable to Add Heroku Account to Project for Depoyment
I have successfully configured my user account so that it is connected to Heroku via a custom client. The SSH key generated by the plugin was added to my Heroku account.

I can add the Heroku plugin to my project, which is provided by a GitHub repo. The project builds without the Heroku plugin. When I add the plugin, the project fails to build with the message 'Invalid Heroku configuration. Account not found' ([worker.js:8](https://github.com/Strider-CD/strider-heroku/blob/657d933c26aee2c29bec4ae861064d81fcaecd2d/worker.js#L7)).

When I attempt to configure the Heroku plugin, the 'Add a Heroku Account' button redirects me to Heroku and the OAuth flow is performed, but I end up on the main Project Settings page. When I go back to the Configure Heroku Plugin page, the account appears to not have been added. Once this is working, I should be able to select which app to deploy the verified build to and the project will be configured correctly.

I will continue investigating this and will contribute any solutions that I find.

### PR DESCRIPTION
**Pull request by tylermauthe**
- Rename HerokuController -> HerokuUserController
- Nest the User Config view in an ng-controller directive

Fixes #5

### CODE REVIEW

**Comment by tylermauthe** [comment]
There are other options here:
- Combine the JavaScript files
- Use [the technique in this stackoverflow post](http://stackoverflow.com/questions/16539999/angular-extending-controller) to extend the HerokuController in the second file
- Open a closure in the User.js file, pull out the $scope from the Config.js controller and attach some extra functionality
- Some other technique for mixing-in functionality to the HerokuController inside the second file...

How do other plugins handle this? Using separate controllers for the project config page and the user config page?

**Comment by knownasilya** [comment]
> Using separate controllers for the project config page and the user config page?

I think that's probably how it's done.

**Comment by knownasilya** [comment]
I will merge this to make the plugin usable, but if you find a better way, feel free to submit another PR.

**Comment by tylermauthe** [comment]
I looked at the other plugins, I couldn't find any other examples of this architecture for configuration pages. I think this solution is probably the way to go, although the ng-controller directive is a bit ugly.

**Comment by knownasilya** [comment]
We definitely use that directive throughout strider, so no biggie.

**Pull request merged**
